### ISSUE TITLE
[Feature Request] Get User Info

### ISSUE THREAD

**Issue by ImLoadingUuU** [GenerateApps/GenerateClient#7]
Please add get user info method in VPClient. that would be useful

**Comment by 4yx** [comment]
Can you specify what you'd want that method to return? Information such as those in the Account Details sidebar, for example?
![image](https://github.com/GenerateApps/VPClient/assets/22258258/91d56d82-3f2e-4f35-8e69-2c0b6ca2d72e)

**Comment by ImLoadingUuU** [comment]
<img width="393" alt="截圖 2023-06-11 清晨7 45 44" src="https://github.com/GenerateApps/VPClient/assets/69704016/e2154378-f5d6-4487-9b26-9b47954b9896">
